# Generated by Django 4.2.6 on 2023-11-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(default='medicine', max_length=100),
        ),
    ]
